In [9]:
import cv2
import mediapipe as mp
import numpy as np
import math
import datetime
import autopy

In [15]:
cv2.__version__

'4.6.0'

#### Calculate Angle Between Three Ooint (1.shoulder,2.elbow,3.wrist)

In [10]:
def calculate_angle(SHOULDER,ELBOW,WRIST):
    """
    _ calculate_angle:Function to calculate angle between three point (1.shoulder,2.elbow,3.wrist)
    _ shoulder:pose landmark number 11 and 12 containe X_position and Y_position
    _ elbow:pose landmark number 13 and 14 containe X_position and Y_position
    _ wrist:pose landmark number 15 and 16 containe X_position and Y_position
    """
    SHOULDER = np.array(SHOULDER) # First
    ELBOW = np.array(ELBOW) # Mid
    WRIST = np.array(WRIST) # End
    
    radians = np.arctan2(WRIST[1]-ELBOW[1],WRIST[0]-ELBOW[0])-np.arctan2(SHOULDER[1]-ELBOW[1],SHOULDER[0]-ELBOW[0])
    angle = np.abs(radians*180.0/np.pi)
    
    if angle > 180:
        angle = 360-angle
    return angle

#### Calculate Distances Between Point in Curent Frame and Point in Previose Frame

In [11]:
def calculate_distances(index,fps,landmark_1,landmark_2):
    """
    _ calculate_distances:Function to calculate distances for specific landmark (shoulder,elbow,wrist,hip,knee,ankle "_left&right_")
    between point in curent frame and point in previose frame
    _ index:number of curent frame
    _ fps:number of frame per seconde
    _ landmark_1:pose landmark for curent frame
    _ landmark_@:pose landmark for previose frame
    """
#     print("================================"+str(index)+"***"+str(fps)+"=======================================")
    my_list = []
    pl = mp_pose.PoseLandmark
    
#     p1 = [landmark_1[pl.NOSE.value].x,landmark_1[pl.NOSE.value].y]
#     p2 = [landmark_2[pl.NOSE.value].x,landmark_2[pl.NOSE.value].y]
#     NOSE_distance = math.sqrt( ((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2) )
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))

    
#     p1 = [landmark_1[pl.LEFT_EYE_INNER.value].x,landmark_1[pl.LEFT_EYE_INNER.value].y]
#     p2 = [landmark_2[pl.LEFT_EYE_INNER.value].x,landmark_2[pl.LEFT_EYE_INNER.value].y]
#     LEFT_EYE_INNERdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
#     p1 = [landmark_1[pl.LEFT_EYE.value].x,landmark_1[pl.LEFT_EYE.value].y]
#     p2 = [landmark_2[pl.LEFT_EYE.value].x,landmark_2[pl.LEFT_EYE.value].y]
#     LEFT_EYEdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
#     p1 = [landmark_1[pl.LEFT_EYE_OUTER.value].x,landmark_1[pl.LEFT_EYE_OUTER.value].y]
#     p2 = [landmark_2[pl.LEFT_EYE_OUTER.value].x,landmark_2[pl.LEFT_EYE_OUTER.value].y]
#     LEFT_EYE_OUTERdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
#     p1 = [landmark_1[pl.RIGHT_EYE_INNER.value].x,landmark_1[pl.RIGHT_EYE_INNER.value].y]
#     p2 = [landmark_2[pl.RIGHT_EYE_INNER.value].x,landmark_2[pl.RIGHT_EYE_INNER.value].y]
#     RIGHT_EYE_INNERdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
#     p1 = [landmark_1[pl.RIGHT_EYE.value].x,landmark_1[pl.RIGHT_EYE.value].y]
#     p2 = [landmark_2[pl.RIGHT_EYE.value].x,landmark_2[pl.RIGHT_EYE.value].y]
#     RIGHT_EYEdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))

#     p1 = [landmark_1[pl.RIGHT_EYE_OUTER.value].x,landmark_1[pl.RIGHT_EYE_OUTER.value].y]
#     p2 = [landmark_2[pl.RIGHT_EYE_OUTER.value].x,landmark_2[pl.RIGHT_EYE_OUTER.value].y]
#     RIGHT_EYE_OUTERdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
#     p1 = [landmark_1[pl.LEFT_EAR.value].x,landmark_1[pl.LEFT_EAR.value].y]
#     p2 = [landmark_2[pl.LEFT_EAR.value].x,landmark_2[pl.LEFT_EAR.value].y]
#     LEFT_EARdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
#     p1 = [landmark_1[pl.RIGHT_EAR.value].x,landmark_1[pl.RIGHT_EAR.value].y]
#     p2 = [landmark_2[pl.RIGHT_EAR.value].x,landmark_2[pl.RIGHT_EAR.value].y]
#     RIGHT_EARdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
#     p1 = [landmark_1[pl.MOUTH_LEFT.value].x,landmark_1[pl.MOUTH_LEFT.value].y]
#     p2 = [landmark_2[pl.MOUTH_LEFT.value].x,landmark_2[pl.MOUTH_LEFT.value].y]
#     MOUTH_LEFTdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
#     p1 = [landmark_1[pl.MOUTH_RIGHT.value].x,landmark_1[pl.MOUTH_RIGHT.value].y]
#     p2 = [landmark_2[pl.MOUTH_RIGHT.value].x,landmark_2[pl.MOUTH_RIGHT.value].y]
#     MOUTH_RIGHTdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
    p1 = [landmark_1[pl.LEFT_SHOULDER.value].x,landmark_1[pl.LEFT_SHOULDER.value].y]
    p2 = [landmark_2[pl.LEFT_SHOULDER.value].x,landmark_2[pl.LEFT_SHOULDER.value].y]
    LEFT_SHOULDERdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
    my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
    p1 = [landmark_1[pl.RIGHT_SHOULDER.value].x,landmark_1[pl.RIGHT_SHOULDER.value].y]
    p2 = [landmark_2[pl.RIGHT_SHOULDER.value].x,landmark_2[pl.RIGHT_SHOULDER.value].y]
    RIGHT_SHOULDERdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
    my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
    p1 = [landmark_1[pl.LEFT_ELBOW.value].x,landmark_1[pl.LEFT_ELBOW.value].y]
    p2 = [landmark_2[pl.LEFT_ELBOW.value].x,landmark_2[pl.LEFT_ELBOW.value].y]
    LEFT_ELBOWdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
    my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
    p1 = [landmark_1[pl.RIGHT_ELBOW.value].x,landmark_1[pl.RIGHT_ELBOW.value].y]
    p2 = [landmark_2[pl.RIGHT_ELBOW.value].x,landmark_2[pl.RIGHT_ELBOW.value].y]
    RIGHT_ELBOWdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
    my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
    p1 = [landmark_1[pl.LEFT_WRIST.value].x,landmark_1[pl.LEFT_WRIST.value].y]
    p2 = [landmark_2[pl.LEFT_WRIST.value].x,landmark_2[pl.LEFT_WRIST.value].y]
    LEFT_WRISTdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
    my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
    p1 = [landmark_1[pl.RIGHT_WRIST.value].x,landmark_1[pl.RIGHT_WRIST.value].y]
    p2 = [landmark_2[pl.RIGHT_WRIST.value].x,landmark_2[pl.RIGHT_WRIST.value].y]
    RIGHT_WRISTdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
    my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
#     p1 = [landmark_1[pl.LEFT_PINKY.value].x,landmark_1[pl.LEFT_PINKY.value].y]
#     p2 = [landmark_2[pl.LEFT_PINKY.value].x,landmark_2[pl.LEFT_PINKY.value].y]
#     LEFT_PINKYdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
#     p1 = [landmark_1[pl.RIGHT_PINKY.value].x,landmark_1[pl.RIGHT_PINKY.value].y]
#     p2 = [landmark_2[pl.RIGHT_PINKY.value].x,landmark_2[pl.RIGHT_PINKY.value].y]
#     RIGHT_PINKYdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
#     p1 = [landmark_1[pl.LEFT_INDEX.value].x,landmark_1[pl.LEFT_INDEX.value].y]
#     p2 = [landmark_2[pl.LEFT_INDEX.value].x,landmark_2[pl.LEFT_INDEX.value].y]
#     LEFT_INDEXdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
#     p1 = [landmark_1[pl.RIGHT_INDEX.value].x,landmark_1[pl.RIGHT_INDEX.value].y]
#     p2 = [landmark_2[pl.RIGHT_INDEX.value].x,landmark_2[pl.RIGHT_INDEX.value].y]
#     RIGHT_INDEXdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
#     p1 = [landmark_1[pl.LEFT_THUMB.value].x,landmark_1[pl.LEFT_THUMB.value].y]
#     p2 = [landmark_2[pl.LEFT_THUMB.value].x,landmark_2[pl.LEFT_THUMB.value].y]
#     LEFT_THUMBdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
#     p1 = [landmark_1[pl.RIGHT_THUMB.value].x,landmark_1[pl.RIGHT_THUMB.value].y]
#     p2 = [landmark_2[pl.RIGHT_THUMB.value].x,landmark_2[pl.RIGHT_THUMB.value].y]
#     RIGHT_THUMBdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))

    
    p1 = [landmark_1[pl.LEFT_HIP.value].x,landmark_1[pl.LEFT_HIP.value].y]
    p2 = [landmark_2[pl.LEFT_HIP.value].x,landmark_2[pl.LEFT_HIP.value].y]
    LEFT_HIPdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
    my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))

    p1 = [landmark_1[pl.RIGHT_HIP.value].x,landmark_1[pl.RIGHT_HIP.value].y]
    p2 = [landmark_2[pl.RIGHT_HIP.value].x,landmark_2[pl.RIGHT_HIP.value].y]
    RIGHT_HIPdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
    my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
    p1 = [landmark_1[pl.LEFT_KNEE.value].x,landmark_1[pl.LEFT_KNEE.value].y]
    p2 = [landmark_2[pl.LEFT_KNEE.value].x,landmark_2[pl.LEFT_KNEE.value].y]
    LEFT_KNEEdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
    my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
    p1 = [landmark_1[pl.RIGHT_KNEE.value].x,landmark_1[pl.RIGHT_KNEE.value].y]
    p2 = [landmark_2[pl.RIGHT_KNEE.value].x,landmark_2[pl.RIGHT_KNEE.value].y]
    RIGHT_KNEEdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
    my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
    p1 = [landmark_1[pl.LEFT_ANKLE.value].x,landmark_1[pl.LEFT_ANKLE.value].y]
    p2 = [landmark_2[pl.LEFT_ANKLE.value].x,landmark_2[pl.LEFT_ANKLE.value].y]
    LEFT_ANKLEdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
    my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
    p1 = [landmark_1[pl.RIGHT_ANKLE.value].x,landmark_1[pl.RIGHT_ANKLE.value].y]
    p2 = [landmark_2[pl.RIGHT_ANKLE.value].x,landmark_2[pl.RIGHT_ANKLE.value].y]
    RIGHT_ANKLEdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
    my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
#     p1 = [landmark_1[pl.LEFT_HEEL.value].x,landmark_1[pl.LEFT_HEEL.value].y]
#     p2 = [landmark_2[pl.LEFT_HEEL.value].x,landmark_2[pl.LEFT_HEEL.value].y]
#     LEFT_HEELdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
#     p1 = [landmark_1[pl.RIGHT_HEEL.value].x,landmark_1[pl.RIGHT_HEEL.value].y]
#     p2 = [landmark_2[pl.RIGHT_HEEL.value].x,landmark_2[pl.RIGHT_HEEL.value].y]
#     RIGHT_HEELdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
#     p1 = [landmark_1[pl.LEFT_FOOT_INDEX.value].x,landmark_1[pl.LEFT_FOOT_INDEX.value].y]
#     p2 = [landmark_2[pl.LEFT_FOOT_INDEX.value].x,landmark_2[pl.LEFT_FOOT_INDEX.value].y]
#     LEFT_FOOT_INDEXdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
#     p1 = [landmark_1[pl.RIGHT_FOOT_INDEX.value].x,landmark_1[pl.RIGHT_FOOT_INDEX.value].y]
#     p2 = [landmark_2[pl.RIGHT_FOOT_INDEX.value].x,landmark_2[pl.RIGHT_FOOT_INDEX.value].y]
#     RIGHT_FOOT_INDEXdistance = math.sqrt(((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2))
#     my_list.append(np.array([[p1[0]],[p1[1]],[(p1[0]-p2[0])/(1/fps)],[(p1[1]-p2[1])/(1/fps)]]))
    
    return my_list

#### Kalman Filter Equation Prediction Update 

In [12]:
def Prediction_update(X,A,P,Q):
    """
    _Prediction_update:Function to Applying Prediction Equation
    _X:State Matrix [X_position,Y_position,X_velocity,Y_velocity]
    _A:State Transition
    _P:Process Covariance Matrix
    _Q:Erorr Terms
    """
    X = A.dot(X)
    TEPM = A.dot(P)
    P = TEPM.dot(A.T)+Q
    return X,P

##### Kalman Filter Equation Measurement Update

In [13]:
def Measurement_update(Z,X,P,H,R):
    """
    _Measurement_update:Function to Applying Measurement Equation
    _X:State Matrix [X_position,Y_position,X_velocity,Y_velocity]
    _P:Process Covariance Matrix
    _H:unit matrix
    _R:Erorr Terms of the Measurement
    """
    I = np.array([[1,0, 0,0],
                  [0, 1,0,0],
                  [0,0,1,0],
                  [0,0,0,1]])
    
    T1 = P.dot(H.T)
    T2 = H.dot(P)
    T3 = T2.dot(H.T)
    T3 = T3 + R
    K = T1.dot(np.linalg.inv(T3))
    
    T1 = H.dot(X)
    T2 = Z - T1
    T3 = K.dot(T2)
    X = X + T3
    
    T1 = K.dot(H)
    T2 = I - T1
    P = T2.dot(P)

    return X,P,K

In [1]:
path_A = "E:\TaskesData\Presenter No11-Rafeef\C_Presenter No11-GroupA.mp4"
path_A1 = path_A[:-3]+"avi"

In [4]:
path_A1

'E:\\TaskesData\\Presenter No11-Rafeef\\C_Presenter No11-GroupA.avi'

#### Download the video, perform the required calculations, and then re-save it

In [14]:
# https://solutions.mediapipe.dev/pose#python-solution-api
# c:\programdata\anaconda3\lib\site-packages\mediapipe\python\solutions\pose.py
path_A = "E:\TaskesData\Presenter No11-Rafeef\C_Presenter No11-GroupA.mp4"
path_A1 = "E:\TaskesData\Presenter No11-Rafeef\det_C_Presenter No11-GroupA.avi"
path_B = "E:\TaskesData\Presenter No11-Rafeef\C_Presenter No11-GroupB.mp4"
path_B1 = "E:\TaskesData\Presenter No11-Rafeef\det_C_Presenter No11-GroupB.avi"
path_C = "E:\TaskesData\Presenter No11-Rafeef\C_Presenter No11-GroupC.mp4"
path_C1 = "E:\TaskesData\Presenter No11-Rafeef\det_C_Presenter No11-GroupC.avi"
path_D = "E:\TaskesData\Presenter No11-Rafeef\C_Presenter No11-GroupD.mp4"
path_D1 = "E:\TaskesData\Presenter No11-Rafeef\det_C_Presenter No11-GroupD.avi"

counter = 0
stage = None
points_in_frames = []
my_list = []
index = 0 
pTime = 0
cTime = 0

mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose 

cap = cv2.VideoCapture(path_A)

# We need to check if camera
# is opened previously or not
if (cap.isOpened() == False): 
    print("Error reading video file")

frame_width = int(cap.get(3))
frame_height = int(cap.get(4))
   
size = (frame_width, frame_height)

# result = cv2.VideoWriter(path_A1,cv2.VideoWriter_fourcc(*'MJPG'),30,(840,480))
result = cv2.VideoWriter(path_A1,cv2.VideoWriter_fourcc(*'MJPG'),10, size)
# count the number of frames
frames = cap.get(cv2.CAP_PROP_FRAME_COUNT)
fps = cap.get(cv2.CAP_PROP_FPS)

# calculate duration of the video
seconds = round(frames / fps)
video_time = datetime.timedelta(seconds=seconds)

delta_t = 1/fps

A = np.array([[1,0, delta_t,0],
              [0, 1,0,delta_t],
              [0,0,1,0],
              [0,0,0,1]])
P = np.array([[10000,0,0,0],
              [0,10000,0,0],
              [0,0,10000,0],
              [0,0,0,10000]])
H = np.array([[1,0,0,0],
              [0, 1,0,0],
              [0,0,1,0],
              [0,0,0,1]])
R = np.array([[5,0, 0,0],
              [0, 5,0,0],
              [0,0,5,0],
              [0,0,0,5]])
Q = np.array([[8,0,0,0],
              [0,8,0,0],
              [0,0,8,0],
              [0,0,0,8]])
X = np.array([[0],
              [0],
              [0],
              [0]])

# Pose : is the algorithem that will be do detection for 33 pointes
## setup mediapipe instance
with mp_pose.Pose(min_detection_confidence=0.5,min_tracking_confidence=0.5) as pose:
    while cap.isOpened():
        ret, frame = cap.read()
        if (not ret) or (cv2.waitKey(10)==ord('q')):
            print("Ignoring empty camera frame.")
            # If loading a video, use 'break' instead of 'continue'.
            break
        
        
        # Recolor image to RGB
        image = cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
        
        # Make detection
        results = pose.process(image)
        
        # Recolor to BGR
        image = cv2.cvtColor(image,cv2.COLOR_RGB2BGR)

        
        # Extract lnadmarks
        try:
            
            landmarks = results.pose_landmarks.landmark
            points_in_frames.append(landmarks)
            
            # Get coordinates
            LEFTshoulder = [landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value].x,landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value].y]
            LEFTelbow = [landmarks[mp_pose.PoseLandmark.LEFT_ELBOW.value].x,landmarks[mp_pose.PoseLandmark.LEFT_ELBOW.value].y]
            LEFTwrist = [landmarks[mp_pose.PoseLandmark.LEFT_WRIST.value].x,landmarks[mp_pose.PoseLandmark.LEFT_WRIST.value].y]

            # calculate angle
            LEFTangle = calculate_angle(LEFTshoulder,LEFTelbow,LEFTwrist)
            
            
            RIGHTshoulder = [landmarks[mp_pose.PoseLandmark.RIGHT_SHOULDER.value].x,landmarks[mp_pose.PoseLandmark.RIGHT_SHOULDER.value].y]
            RIGHTelbow = [landmarks[mp_pose.PoseLandmark.RIGHT_ELBOW.value].x,landmarks[mp_pose.PoseLandmark.RIGHT_ELBOW.value].y]
            RIGHTwrist = [landmarks[mp_pose.PoseLandmark.RIGHT_WRIST.value].x,landmarks[mp_pose.PoseLandmark.RIGHT_WRIST.value].y]

            # calculate angle
            RIGHTangle = calculate_angle(RIGHTshoulder,RIGHTelbow,RIGHTwrist)
            
            # curl counter logic
            if LEFTangle>160:
                stage = 'down'
            if LEFTangle<45 and stage=='down':
                stage = 'up'
                counter+=1
#                 print(counter)
            if index!=0 and (index%fps==0):
                my_list = calculate_distances(index,int(fps),points_in_frames[index],points_in_frames[index-1])
                for i in range(len(my_list)):
#                     print("=========="+str(i)+"========")
                    if index==15:
                        X = my_list[i]
                    Z = my_list[i]                                
                    X , P = Prediction_update(X,A,P,Q)
                    X , P , K = Measurement_update(Z,X,P,H,R)
                    print("Z"+str(i)+" : \n",Z)
                    print("X"+str(i)+" : \n",X)
                print("\n\n")


            if len(my_list)>0:
                cv2.putText(image,str(str(round(my_list[0][2][0], 4))+" , "+str(round(my_list[0][3][0], 4))),(int(landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value].x*1300),int(landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value].y*700)),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,255),2,cv2.LINE_AA)
                cv2.putText(image,str(str(round(my_list[1][2][0],4))+" , "+str(round(my_list[1][3][0],4))),(int(landmarks[mp_pose.PoseLandmark.RIGHT_SHOULDER.value].x*1100),int(landmarks[mp_pose.PoseLandmark.RIGHT_SHOULDER.value].y*700)),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,255),2,cv2.LINE_AA)
                cv2.putText(image,str(str(round(my_list[2][2][0],4))+" , "+str(round(my_list[2][3][0],4))+"   "+str(int(LEFTangle))),(int(landmarks[mp_pose.PoseLandmark.LEFT_ELBOW.value].x*1300),int(landmarks[mp_pose.PoseLandmark.LEFT_ELBOW.value].y*700)),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,255),2,cv2.LINE_AA)
                cv2.putText(image,str(str(round(my_list[3][2][0],4))+" , "+str(round(my_list[3][3][0],4))+"   "+str(int(RIGHTangle))),(int(landmarks[mp_pose.PoseLandmark.RIGHT_ELBOW.value].x*1100),int(landmarks[mp_pose.PoseLandmark.RIGHT_ELBOW.value].y*700)),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,255),2,cv2.LINE_AA)
                cv2.putText(image,str(str(round(my_list[4][2][0],4))+" , "+str(round(my_list[4][3][0],4))),(int(landmarks[mp_pose.PoseLandmark.LEFT_WRIST.value].x*1300),int(landmarks[mp_pose.PoseLandmark.LEFT_WRIST.value].y*700)),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,255),2,cv2.LINE_AA)
                cv2.putText(image,str(str(round(my_list[5][2][0],4))+" , "+str(round(my_list[5][3][0],4))),(int(landmarks[mp_pose.PoseLandmark.RIGHT_WRIST.value].x*1100),int(landmarks[mp_pose.PoseLandmark.RIGHT_WRIST.value].y*700)),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,255),2,cv2.LINE_AA)
                cv2.putText(image,str(str(round(my_list[6][2][0],4))+" , "+str(round(my_list[6][3][0],4))),(int(landmarks[mp_pose.PoseLandmark.LEFT_HIP.value].x*1300),int(landmarks[mp_pose.PoseLandmark.LEFT_HIP.value].y*700)),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,255),2,cv2.LINE_AA)
                cv2.putText(image,str(str(round(my_list[7][2][0],4))+" , "+str(round(my_list[7][3][0],4))),(int(landmarks[mp_pose.PoseLandmark.RIGHT_HIP.value].x*1100),int(landmarks[mp_pose.PoseLandmark.RIGHT_HIP.value].y*700)),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,255),2,cv2.LINE_AA)
                cv2.putText(image,str(str(round(my_list[8][2][0],4))+" , "+str(round(my_list[8][3][0],4))),(int(landmarks[mp_pose.PoseLandmark.LEFT_KNEE.value].x*1300),int(landmarks[mp_pose.PoseLandmark.LEFT_KNEE.value].y*700)),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,255),2,cv2.LINE_AA)
                cv2.putText(image,str(str(round(my_list[9][2][0],4))+" , "+str(round(my_list[9][3][0],4))),(int(landmarks[mp_pose.PoseLandmark.RIGHT_KNEE.value].x*1100),int(landmarks[mp_pose.PoseLandmark.RIGHT_KNEE.value].y*700)),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,255),2,cv2.LINE_AA)
                cv2.putText(image,str(str(round(my_list[10][2][0],4))+" , "+str(round(my_list[10][3][0],4))),(int(landmarks[mp_pose.PoseLandmark.LEFT_ANKLE.value].x*1300),int(landmarks[mp_pose.PoseLandmark.LEFT_ANKLE.value].y*700)),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,255),2,cv2.LINE_AA)
                cv2.putText(image,str(str(round(my_list[11][2][0],4))+" , "+str(round(my_list[11][3][0],4))),(int(landmarks[mp_pose.PoseLandmark.RIGHT_ANKLE.value].x*1100),int(landmarks[mp_pose.PoseLandmark.RIGHT_ANKLE.value].y*700)),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,255,255),2,cv2.LINE_AA)
            index+=1
        except:
            pass
        # Render culr counter
        # setup status box
        cv2.rectangle(image,(0,0),(235,73),(245,117,16),-1)
        
        # Rep data
        cv2.putText(image,'PEPS',(15,12),
                   cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,0,0),1,cv2.LINE_AA)
        cv2.putText(image,str(counter),
                   (10,60),
                   cv2.FONT_HERSHEY_SIMPLEX,2,(255,255,255))
        cv2.putText(image,'STAG',(75,12),
                   cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,0,0))
        cv2.putText(image,stage,
                   (80,60),
                   cv2.FONT_HERSHEY_SIMPLEX,2,(255,255,255),2)
        
        # Render detections
        mp_drawing.draw_landmarks(image,results.pose_landmarks,mp_pose.POSE_CONNECTIONS,
                                 mp_drawing.DrawingSpec(color=(245,117,66),thickness=4,circle_radius=4),
                                 mp_drawing.DrawingSpec(color=(245,66,230),thickness=4))
        result.write(image)
        cv2.imshow('Body Movement Taske',image)
        
        if cv2.waitKey(10)==ord('q'):
            break
cap.release()
result.release()
cv2.destroyAllWindows()  

Z0 : 
 [[6.63059950e-01]
 [3.25154275e-01]
 [4.86642122e-03]
 [2.40951777e-04]]
X0 : 
 [[6.63060112e-01]
 [3.25154283e-01]
 [4.86641044e-03]
 [2.40951242e-04]]
Z1 : 
 [[0.50059414]
 [0.31834096]
 [0.01406685]
 [0.00360936]]
X1 : 
 [[0.50085444]
 [0.31840775]
 [0.01406202]
 [0.00360812]]
Z2 : 
 [[6.78707898e-01]
 [5.50743461e-01]
 [1.26126409e-02]
 [1.05500221e-04]]
X2 : 
 [[6.78960747e-01]
 [5.50745576e-01]
 [1.26085856e-02]
 [1.05466301e-04]]
Z3 : 
 [[ 0.47850928]
 [ 0.53418577]
 [-0.0124678 ]
 [-0.02696246]]
X3 : 
 [[ 0.47825757]
 [ 0.53364144]
 [-0.01246388]
 [-0.02695398]]
Z4 : 
 [[ 0.67380321]
 [ 0.74628031]
 [-0.07808   ]
 [-0.0310725 ]]
X4 : 
 [[ 0.67222589]
 [ 0.74565261]
 [-0.07805552]
 [-0.03106275]]
Z5 : 
 [[ 0.47209772]
 [ 0.71383047]
 [-0.00081271]
 [-0.1850903 ]]
X5 : 
 [[ 0.47208131]
 [ 0.71009117]
 [-0.00081245]
 [-0.18503229]]
Z6 : 
 [[ 6.22667968e-01]
 [ 7.22743988e-01]
 [-7.03632832e-04]
 [ 5.95182180e-02]]
X6 : 
 [[ 6.22653753e-01]
 [ 7.23946416e-01]
 [-7.03412308e-

Z0 : 
 [[0.65057027]
 [0.31708464]
 [0.00184268]
 [0.00190035]]
X0 : 
 [[0.61934364]
 [0.58267163]
 [0.00112342]
 [0.02361207]]
Z1 : 
 [[ 0.49595326]
 [ 0.31321719]
 [-0.00144795]
 [ 0.00375107]]
X1 : 
 [[ 0.53335615]
 [ 0.39525646]
 [-0.00124817]
 [ 0.00850312]]
Z2 : 
 [[ 6.82729244e-01]
 [ 5.25072038e-01]
 [-1.49309635e-03]
 [ 3.41534615e-04]]
X2 : 
 [[ 0.63743678]
 [ 0.48586608]
 [-0.00071618]
 [ 0.00342551]]
Z3 : 
 [[0.45430988]
 [0.50611538]
 [0.00198662]
 [0.04305393]]
X3 : 
 [[5.09802986e-01]
 [5.00234520e-01]
 [3.05878683e-04]
 [3.11240948e-02]]
Z4 : 
 [[0.59737146]
 [0.56563115]
 [0.00075638]
 [0.0292933 ]]
X4 : 
 [[0.57084296]
 [0.54643351]
 [0.00103126]
 [0.03014647]]
Z5 : 
 [[0.50350124]
 [0.56782913]
 [0.04830748]
 [0.04088044]]
X5 : 
 [[0.52415159]
 [0.56200489]
 [0.03364615]
 [0.0377147 ]]
Z6 : 
 [[0.61241639]
 [0.71027762]
 [0.00257313]
 [0.02878457]]
X6 : 
 [[0.58620224]
 [0.66606493]
 [0.01240562]
 [0.03217935]]
Z7 : 
 [[ 0.52425683]
 [ 0.70418483]
 [-0.00173002]
 [ 0

Z0 : 
 [[ 6.53587699e-01]
 [ 3.10427129e-01]
 [-3.60488892e-03]
 [ 5.50299883e-04]]
X0 : 
 [[ 0.62186528]
 [ 0.59607856]
 [-0.00360616]
 [ 0.09389303]]
Z1 : 
 [[ 0.49858457]
 [ 0.31616092]
 [-0.00633046]
 [-0.00606269]]
X1 : 
 [[ 0.53585796]
 [ 0.4024143 ]
 [-0.00608228]
 [ 0.02292027]]
Z2 : 
 [[ 6.87408805e-01]
 [ 5.29902875e-01]
 [-1.43051147e-05]
 [ 2.66432762e-04]]
X2 : 
 [[ 0.64138841]
 [ 0.49162523]
 [-0.00114108]
 [ 0.00773215]]
Z3 : 
 [[ 4.66211736e-01]
 [ 5.19137383e-01]
 [-1.01163983e-03]
 [-3.22759151e-04]]
X3 : 
 [[ 0.51927492]
 [ 0.51091843]
 [-0.00187407]
 [ 0.00224815]]
Z4 : 
 [[0.63526022]
 [0.42562041]
 [0.14202833]
 [0.30755684]]
X4 : 
 [[0.60075061]
 [0.45294986]
 [0.09891169]
 [0.21451919]]
Z5 : 
 [[ 0.51718712]
 [ 0.56029463]
 [-0.00511765]
 [ 0.03543556]]
X5 : 
 [[0.54401948]
 [0.5312568 ]
 [0.02602282]
 [0.09021004]]
Z6 : 
 [[ 0.61745328]
 [ 0.71012652]
 [-0.01133233]
 [-0.0180316 ]]
X6 : 
 [[5.95549983e-01]
 [6.57235383e-01]
 [3.38929584e-04]
 [1.56234029e-02]]


Z0 : 
 [[6.58366263e-01]
 [3.20853412e-01]
 [2.17258930e-04]
 [4.00453806e-03]]
X0 : 
 [[0.62524457]
 [0.59698343]
 [0.00206726]
 [0.00904092]]
Z1 : 
 [[ 5.06556571e-01]
 [ 3.18953484e-01]
 [-5.81145287e-05]
 [ 7.30544329e-03]]
X1 : 
 [[5.42555615e-01]
 [4.03382311e-01]
 [2.81520037e-05]
 [6.52214422e-03]]
Z2 : 
 [[ 0.68567663]
 [ 0.5232169 ]
 [-0.01053303]
 [ 0.00192851]]
X2 : 
 [[ 0.64225609]
 [ 0.48701234]
 [-0.00665577]
 [ 0.0038836 ]]
Z3 : 
 [[ 4.70262229e-01]
 [ 5.05986094e-01]
 [-3.66568565e-04]
 [-1.67995691e-03]]
X3 : 
 [[ 5.22278437e-01]
 [ 5.00288582e-01]
 [-3.08129195e-03]
 [ 9.61038531e-05]]
Z4 : 
 [[ 0.60265827]
 [ 0.57371193]
 [-0.00305235]
 [-0.01720816]]
X4 : 
 [[ 0.57823781]
 [ 0.55138228]
 [-0.0026823 ]
 [-0.01161261]]
Z5 : 
 [[ 0.52045536]
 [ 0.55219895]
 [-0.02167135]
 [ 0.00280201]]
X5 : 
 [[ 0.53782233]
 [ 0.55178462]
 [-0.01618054]
 [-0.00156415]]
Z6 : 
 [[6.19377017e-01]
 [7.08514392e-01]
 [2.69114971e-04]
 [1.01843476e-02]]
X6 : 
 [[ 0.59441308]
 [ 0.66104255]

Z0 : 
 [[ 6.50790930e-01]
 [ 3.14128667e-01]
 [ 9.63807106e-04]
 [-1.96695328e-04]]
X0 : 
 [[ 0.62105648]
 [ 0.56707729]
 [ 0.00420914]
 [-0.06505119]]
Z1 : 
 [[ 4.94539917e-01]
 [ 3.17033440e-01]
 [-4.93079424e-04]
 [ 1.88215077e-02]]
X1 : 
 [[ 5.32942490e-01]
 [ 3.91886937e-01]
 [ 3.37574272e-04]
 [-7.78201115e-03]]
Z2 : 
 [[ 0.67981589]
 [ 0.52935487]
 [-0.00611901]
 [ 0.04802048]]
X2 : 
 [[ 0.63528377]
 [ 0.48780163]
 [-0.00346962]
 [ 0.03173772]]
Z3 : 
 [[ 0.46038905]
 [ 0.5292511 ]
 [-0.00139475]
 [ 0.14647007]]
X3 : 
 [[ 0.51332889]
 [ 0.51787078]
 [-0.0028454 ]
 [ 0.11184319]]
Z4 : 
 [[ 0.6100226 ]
 [ 0.43198904]
 [ 0.01599848]
 [-0.11605069]]
X4 : 
 [[ 0.58075159]
 [ 0.45920288]
 [ 0.01073638]
 [-0.04734252]]
Z5 : 
 [[ 0.47570524]
 [ 0.485955  ]
 [-0.33185095]
 [-0.01950905]]
X5 : 
 [[ 0.50614491]
 [ 0.47702242]
 [-0.2284012 ]
 [-0.0278136 ]]
Z6 : 
 [[0.61396146]
 [0.7165696 ]
 [0.00829786]
 [0.02532095]]
X6 : 
 [[ 0.5777871 ]
 [ 0.64366498]
 [-0.06294231]
 [ 0.01033385]]
Z7 :

Z0 : 
 [[0.65121043]
 [0.31481078]
 [0.00258565]
 [0.00414938]]
X0 : 
 [[ 0.61879153]
 [ 0.59437952]
 [-0.01429288]
 [ 0.00304377]]
Z1 : 
 [[ 5.01014709e-01]
 [ 3.15239280e-01]
 [-5.86688519e-03]
 [-4.75198030e-04]]
X1 : 
 [[ 0.53645671]
 [ 0.39987503]
 [-0.00897268]
 [-0.0007207 ]]
Z2 : 
 [[ 0.68277836]
 [ 0.52198035]
 [-0.00746548]
 [-0.00632912]]
X2 : 
 [[ 0.63826279]
 [ 0.48493656]
 [-0.00723211]
 [-0.00405317]]
Z3 : 
 [[ 4.68361378e-01]
 [ 5.14353275e-01]
 [-2.48104334e-04]
 [-5.23924828e-04]]
X3 : 
 [[ 0.51973511]
 [ 0.50537353]
 [-0.00316362]
 [-0.0014552 ]]
Z4 : 
 [[ 0.63197273]
 [ 0.40970483]
 [-0.06589651]
 [ 0.03707439]]
X4 : 
 [[ 0.59760136]
 [ 0.43884805]
 [-0.04633364]
 [ 0.02493455]]
Z5 : 
 [[ 0.50896502]
 [ 0.52774715]
 [-0.01793057]
 [-0.09777188]]
X5 : 
 [[ 0.53502288]
 [ 0.50073402]
 [-0.02695072]
 [-0.06013051]]
Z6 : 
 [[ 0.6178354 ]
 [ 0.70472413]
 [-0.00329554]
 [-0.01066625]]
X6 : 
 [[ 0.59230658]
 [ 0.6419246 ]
 [-0.01007518]
 [-0.02469675]]
Z7 : 
 [[ 0.5315302 

Z0 : 
 [[ 0.66138351]
 [ 0.31085482]
 [ 0.00198126]
 [-0.01021072]]
X0 : 
 [[0.62773361]
 [0.59075438]
 [0.00209274]
 [0.06770786]]
Z1 : 
 [[ 0.50647742]
 [ 0.31615812]
 [ 0.00286728]
 [-0.00162005]]
X1 : 
 [[0.54326888]
 [0.40041387]
 [0.00206158]
 [0.01810312]]
Z2 : 
 [[ 6.92620516e-01]
 [ 5.07461846e-01]
 [-4.82797623e-04]
 [ 1.32322311e-03]]
X2 : 
 [[0.64739061]
 [0.47530882]
 [0.00099068]
 [0.0069121 ]]
Z3 : 
 [[ 4.66708481e-01]
 [ 5.04478216e-01]
 [-2.68220901e-06]
 [ 8.17537308e-03]]
X3 : 
 [[ 0.52147783]
 [ 0.49578429]
 [-0.00055099]
 [ 0.00792704]]
Z4 : 
 [[ 0.62014896]
 [ 0.55440557]
 [-0.01169086]
 [ 0.0154236 ]]
X4 : 
 [[ 0.59018411]
 [ 0.53683634]
 [-0.00784679]
 [ 0.01342211]]
Z5 : 
 [[ 0.51975822]
 [ 0.56336176]
 [ 0.01638383]
 [-0.00764966]]
X5 : 
 [[ 0.5410555 ]
 [ 0.55549559]
 [ 0.00870322]
 [-0.00113563]]
Z6 : 
 [[ 6.22047722e-01]
 [ 7.03134298e-01]
 [ 2.17348337e-03]
 [-7.15255737e-06]]
X6 : 
 [[5.97648931e-01]
 [6.58376151e-01]
 [4.53274067e-03]
 [3.44864022e-04]]


Z0 : 
 [[ 6.46103263e-01]
 [ 3.15605074e-01]
 [-1.00064278e-02]
 [ 2.52574682e-04]]
X0 : 
 [[ 0.61669395]
 [ 0.57773638]
 [-0.00774029]
 [-0.07317676]]
Z1 : 
 [[ 0.49345008]
 [ 0.32164288]
 [-0.00909716]
 [ 0.01912594]]
X1 : 
 [[ 0.53063521]
 [ 0.39820513]
 [-0.00926241]
 [-0.01006128]]
Z2 : 
 [[ 6.79417968e-01]
 [ 5.18901765e-01]
 [-8.94069672e-05]
 [ 1.25169754e-03]]
X2 : 
 [[ 0.63418676]
 [ 0.48217571]
 [-0.00217032]
 [-0.0016103 ]]
Z3 : 
 [[4.59086329e-01]
 [5.16005218e-01]
 [4.28706408e-04]
 [3.64252925e-02]]
X3 : 
 [[ 0.51211722]
 [ 0.50589978]
 [-0.00118236]
 [ 0.02504417]]
Z4 : 
 [[ 0.59425843]
 [ 0.55525595]
 [ 0.00505328]
 [-0.06933779]]
X4 : 
 [[ 0.56937174]
 [ 0.5403613 ]
 [ 0.0035478 ]
 [-0.04047648]]
Z5 : 
 [[0.50079083]
 [0.52362943]
 [0.00163704]
 [0.0078097 ]]
X5 : 
 [[ 0.52163632]
 [ 0.52810912]
 [ 0.00189328]
 [-0.00690714]]
Z6 : 
 [[ 0.61472422]
 [ 0.70614082]
 [-0.00256956]
 [ 0.0065285 ]]
X6 : 
 [[ 0.58653208]
 [ 0.65211362]
 [-0.00077843]
 [ 0.003291  ]]
Z7 : 
 [

Z0 : 
 [[ 0.65663373]
 [ 0.31586498]
 [-0.01492739]
 [-0.03516734]]
X0 : 
 [[ 0.62066975]
 [ 0.58237352]
 [-0.01021618]
 [-0.04461361]]
Z1 : 
 [[ 0.50091112]
 [ 0.31908336]
 [-0.01301765]
 [-0.01452327]]
X1 : 
 [[ 0.53698327]
 [ 0.39811109]
 [-0.01272743]
 [-0.02487696]]
Z2 : 
 [[ 6.87115788e-01]
 [ 5.09890914e-01]
 [-1.18911266e-04]
 [-1.71411037e-02]]
X2 : 
 [[ 0.6414217 ]
 [ 0.47555088]
 [-0.00323478]
 [-0.01895502]]
Z3 : 
 [[ 0.46510273]
 [ 0.50648886]
 [-0.00327945]
 [-0.0008592 ]]
X3 : 
 [[ 0.51846896]
 [ 0.49681553]
 [-0.00409377]
 [-0.0061984 ]]
Z4 : 
 [[ 0.61188596]
 [ 0.56090277]
 [-0.00133574]
 [-0.00689864]]
X4 : 
 [[ 0.58350709]
 [ 0.54135323]
 [-0.00173213]
 [-0.00638296]]
Z5 : 
 [[ 5.07939816e-01]
 [ 5.29849231e-01]
 [-1.24275684e-04]
 [ 1.58759952e-02]]
X5 : 
 [[ 0.53081233]
 [ 0.5333111 ]
 [-0.00096683]
 [ 0.00907016]]
Z6 : 
 [[ 6.14669323e-01]
 [ 7.13071764e-01]
 [ 2.95042992e-05]
 [-2.47630477e-02]]
X6 : 
 [[ 5.89242407e-01]
 [ 6.58621189e-01]
 [ 1.21719437e-04]
 [-1

Z0 : 
 [[ 6.57866657e-01]
 [ 3.10628027e-01]
 [-2.60800123e-03]
 [-4.68939543e-04]]
X0 : 
 [[ 0.62446688]
 [ 0.59199282]
 [-0.00118283]
 [-0.00576946]]
Z1 : 
 [[0.50500947]
 [0.32080126]
 [0.01847863]
 [0.01374185]]
X1 : 
 [[0.54127844]
 [0.40295845]
 [0.0119518 ]
 [0.0065487 ]]
Z2 : 
 [[ 0.69240654]
 [ 0.52742684]
 [-0.00875562]
 [ 0.02331555]]
X2 : 
 [[ 0.64675271]
 [ 0.489919  ]
 [-0.00176592]
 [ 0.01881128]]
Z3 : 
 [[0.47824454]
 [0.52168167]
 [0.06266847]
 [0.01089066]]
X3 : 
 [[0.52957658]
 [0.51239909]
 [0.04232635]
 [0.01343734]]
Z4 : 
 [[ 0.59412342]
 [ 0.56237614]
 [-0.05894959]
 [-0.006634  ]]
X4 : 
 [[ 5.74942116e-01]
 [ 5.47408186e-01]
 [-2.79305386e-02]
 [-3.13271237e-04]]
Z5 : 
 [[0.45986849]
 [0.4512873 ]
 [0.2638194 ]
 [0.0837855 ]]
X5 : 
 [[0.49554772]
 [0.48080485]
 [0.17476518]
 [0.0578167 ]]
Z6 : 
 [[ 0.61638153]
 [ 0.71410215]
 [ 0.0099206 ]
 [-0.01837581]]
X6 : 
 [[0.58251977]
 [0.64421348]
 [0.06045058]
 [0.00582095]]
Z7 : 
 [[ 5.21063209e-01]
 [ 7.08511472e-01]

Z0 : 
 [[6.56489491e-01]
 [3.13104570e-01]
 [4.87267971e-04]
 [2.26244330e-02]]
X0 : 
 [[ 6.24594169e-01]
 [ 5.92719878e-01]
 [-4.70209539e-05]
 [ 7.77245619e-03]]
Z1 : 
 [[ 5.01434803e-01]
 [ 3.17691892e-01]
 [-6.80744648e-03]
 [ 3.97861004e-04]]
X1 : 
 [[ 0.53872435]
 [ 0.40115887]
 [-0.00533518]
 [ 0.00134008]]
Z2 : 
 [[ 0.68900472]
 [ 0.52020949]
 [-0.00279218]
 [ 0.02737641]]
X2 : 
 [[ 0.64336785]
 [ 0.4842818 ]
 [-0.00285562]
 [ 0.02003578]]
Z3 : 
 [[ 0.4679957 ]
 [ 0.51898026]
 [-0.0175716 ]
 [ 0.01709193]]
X3 : 
 [[ 0.5210137 ]
 [ 0.50885616]
 [-0.01393006]
 [ 0.01814199]]
Z4 : 
 [[0.60629547]
 [0.5515328 ]
 [0.02115637]
 [0.01431137]]
X4 : 
 [[0.58033515]
 [0.53894856]
 [0.01091582]
 [0.01566859]]
Z5 : 
 [[ 0.51589328]
 [ 0.55528462]
 [-0.01652509]
 [-0.01048565]]
X5 : 
 [[ 0.53551331]
 [ 0.55052773]
 [-0.00850541]
 [-0.00247811]]
Z6 : 
 [[ 0.62232053]
 [ 0.72046822]
 [-0.02207369]
 [ 0.00354677]]
X6 : 
 [[ 0.59577881]
 [ 0.66894763]
 [-0.01754608]
 [ 0.0025184 ]]
Z7 : 
 [[ 0.

Z0 : 
 [[ 6.58441901e-01]
 [ 3.18309337e-01]
 [ 1.78813934e-05]
 [-8.98629427e-03]]
X0 : 
 [[6.22982256e-01]
 [5.98445170e-01]
 [3.58689111e-04]
 [1.54368722e-02]]
Z1 : 
 [[ 5.01333833e-01]
 [ 3.11423689e-01]
 [-1.89542770e-04]
 [-3.09348106e-04]]
X1 : 
 [[ 0.5382029 ]
 [ 0.39864067]
 [-0.00059519]
 [ 0.00311418]]
Z2 : 
 [[ 0.68677765]
 [ 0.51812828]
 [ 0.00268847]
 [-0.06918311]]
X2 : 
 [[ 0.6417569 ]
 [ 0.48164173]
 [ 0.0023908 ]
 [-0.04668611]]
Z3 : 
 [[0.46550918]
 [0.50012982]
 [0.01016468]
 [0.00369295]]
X3 : 
 [[ 0.51900422]
 [ 0.49382083]
 [ 0.00697665]
 [-0.01149138]]
Z4 : 
 [[0.61832333]
 [0.55886322]
 [0.03514409]
 [0.0007385 ]]
X4 : 
 [[ 0.58849898]
 [ 0.53897808]
 [ 0.02706232]
 [-0.00266289]]
Z5 : 
 [[ 0.51166207]
 [ 0.54864365]
 [ 0.00720531]
 [-0.07078528]]
X5 : 
 [[ 0.53540015]
 [ 0.54534054]
 [ 0.01286057]
 [-0.05006949]]
Z6 : 
 [[ 0.61637485]
 [ 0.71460015]
 [ 0.00431657]
 [-0.02745867]]
X6 : 
 [[ 0.59205589]
 [ 0.66240239]
 [ 0.0072856 ]
 [-0.03350779]]
Z7 : 
 [[ 0.

Z0 : 
 [[ 0.65198243]
 [ 0.3061434 ]
 [-0.01495779]
 [-0.00504032]]
X0 : 
 [[ 0.6192324 ]
 [ 0.59756421]
 [-0.01300657]
 [ 0.00222229]]
Z1 : 
 [[ 0.49341145]
 [ 0.31380823]
 [-0.00108719]
 [-0.01323983]]
X1 : 
 [[ 0.53133356]
 [ 0.39977   ]
 [-0.00529115]
 [-0.00988301]]
Z2 : 
 [[ 0.6879003 ]
 [ 0.51613164]
 [-0.01286745]
 [-0.02184302]]
X2 : 
 [[ 0.64031173]
 [ 0.48061346]
 [-0.00983098]
 [-0.01766402]]
Z3 : 
 [[ 0.4620418 ]
 [ 0.51716244]
 [-0.00425085]
 [-0.02853245]]
X3 : 
 [[ 0.51589243]
 [ 0.50567867]
 [-0.00677894]
 [-0.02505742]]
Z4 : 
 [[ 0.60669136]
 [ 0.55143368]
 [ 0.01782954]
 [-0.1103881 ]]
X4 : 
 [[ 0.57915434]
 [ 0.53666069]
 [ 0.01079187]
 [-0.08427434]]
Z5 : 
 [[ 0.51213002]
 [ 0.54931259]
 [-0.05274653]
 [-0.06298542]]
X5 : 
 [[ 0.53236043]
 [ 0.54387606]
 [-0.03378635]
 [-0.06935896]]
Z6 : 
 [[ 0.61856532]
 [ 0.70990068]
 [-0.01282275]
 [-0.06823093]]
X6 : 
 [[ 0.59185772]
 [ 0.65819256]
 [-0.01876762]
 [-0.06777096]]
Z7 : 
 [[ 0.52641726]
 [ 0.70592153]
 [-0.019309

Z0 : 
 [[ 0.65091801]
 [ 0.31154707]
 [ 0.00240326]
 [-0.01593143]]
X0 : 
 [[ 0.62073201]
 [ 0.59463271]
 [ 0.00740997]
 [-0.0252227 ]]
Z1 : 
 [[ 4.97735322e-01]
 [ 3.22362930e-01]
 [ 1.18106604e-03]
 [-7.06315041e-05]]
X1 : 
 [[ 0.53512872]
 [ 0.40448038]
 [ 0.00249049]
 [-0.00897426]]
Z2 : 
 [[ 0.68209952]
 [ 0.51688838]
 [ 0.00204653]
 [-0.00568807]]
X2 : 
 [[ 0.63760964]
 [ 0.48265835]
 [ 0.00287137]
 [-0.00615391]]
Z3 : 
 [[ 0.47196269]
 [ 0.52610457]
 [-0.00392541]
 [ 0.02165884]]
X3 : 
 [[ 0.52218648]
 [ 0.51294503]
 [-0.00264277]
 [ 0.01342614]]
Z4 : 
 [[0.61990982]
 [0.40802202]
 [0.04895478]
 [0.04372492]]
X4 : 
 [[0.59048487]
 [0.44023162]
 [0.03375942]
 [0.03403429]]
Z5 : 
 [[0.51002657]
 [0.55355299]
 [0.03225714]
 [0.07780463]]
X5 : 
 [[0.53508366]
 [0.52010537]
 [0.03232414]
 [0.06504601]]
Z6 : 
 [[6.19778931e-01]
 [7.13810384e-01]
 [1.88201666e-03]
 [3.11136246e-04]]
X6 : 
 [[0.59462276]
 [0.6561197 ]
 [0.01150671]
 [0.02084306]]
Z7 : 
 [[ 5.28636336e-01]
 [ 7.16163576e

Z0 : 
 [[ 0.65704429]
 [ 0.31529346]
 [ 0.01593143]
 [-0.00139564]]
X0 : 
 [[ 0.61927205]
 [ 0.60659231]
 [-0.00175518]
 [ 0.01645801]]
Z1 : 
 [[0.501302  ]
 [0.31573126]
 [0.02659813]
 [0.01254603]]
X1 : 
 [[0.53714954]
 [0.40418804]
 [0.0174412 ]
 [0.01236048]]
Z2 : 
 [[ 0.68503457]
 [ 0.51996857]
 [ 0.01549512]
 [-0.01213074]]
X2 : 
 [[ 0.64056263]
 [ 0.48501696]
 [ 0.01677535]
 [-0.00415926]]
Z3 : 
 [[0.46582913]
 [0.50226557]
 [0.02324134]
 [0.00119984]]
X3 : 
 [[ 5.19149765e-01]
 [ 4.96979710e-01]
 [ 2.04527548e-02]
 [-3.43812023e-04]]
Z4 : 
 [[ 0.61062616]
 [ 0.56408566]
 [ 0.05619138]
 [-0.00952542]]
X4 : 
 [[ 0.58348632]
 [ 0.54369973]
 [ 0.04577129]
 [-0.00642398]]
Z5 : 
 [[ 0.51333582]
 [ 0.55880994]
 [ 0.0272271 ]
 [-0.00060976]]
X5 : 
 [[ 0.53543179]
 [ 0.55412848]
 [ 0.0325096 ]
 [-0.00230085]]
Z6 : 
 [[ 0.617809  ]
 [ 0.71971875]
 [ 0.01829535]
 [-0.00128835]]
X6 : 
 [[ 0.59343533]
 [ 0.66949647]
 [ 0.02298527]
 [-0.00081639]]
Z7 : 
 [[ 0.53130317]
 [ 0.71280426]
 [ 0.02

Z0 : 
 [[0.64698565]
 [0.31079987]
 [0.00372648]
 [0.0459981 ]]
X0 : 
 [[0.61625208]
 [0.58874701]
 [0.00350791]
 [0.03886354]]
Z1 : 
 [[4.95117128e-01]
 [3.19171429e-01]
 [1.44839287e-04]
 [5.42253256e-03]]
X1 : 
 [[0.53188098]
 [0.40149169]
 [0.00059469]
 [0.01428964]]
Z2 : 
 [[0.67631698]
 [0.52472204]
 [0.02590567]
 [0.2198115 ]]
X2 : 
 [[0.63267802]
 [0.48863311]
 [0.0189047 ]
 [0.15802743]]
Z3 : 
 [[0.46738642]
 [0.51699722]
 [0.01037657]
 [0.04500121]]
X3 : 
 [[0.51781831]
 [0.51106298]
 [0.01218118]
 [0.07937914]]
Z4 : 
 [[ 0.62610042]
 [ 0.45638639]
 [-0.23833394]
 [ 0.3280963 ]]
X4 : 
 [[ 0.59235496]
 [ 0.47572852]
 [-0.16181808]
 [ 0.25234928]]
Z5 : 
 [[ 0.51159453]
 [ 0.54933089]
 [-0.00479043]
 [ 0.00982761]]
X5 : 
 [[ 0.53353725]
 [ 0.53098442]
 [-0.05276429]
 [ 0.08367982]]
Z6 : 
 [[0.61716819]
 [0.70807195]
 [0.00073493]
 [0.03616154]]
X6 : 
 [[ 0.59101015]
 [ 0.65587442]
 [-0.01508797]
 [ 0.05138569]]
Z7 : 
 [[ 5.29797316e-01]
 [ 7.09334671e-01]
 [-4.76539135e-04]
 [ 4

Z0 : 
 [[0.6477949 ]
 [0.30773106]
 [0.01349777]
 [0.00405148]]
X0 : 
 [[ 0.61559806]
 [ 0.59504226]
 [ 0.00392614]
 [-0.00794892]]
Z1 : 
 [[4.92919207e-01]
 [3.18386406e-01]
 [7.15255737e-06]
 [1.84804201e-03]]
X1 : 
 [[ 0.53015676]
 [ 0.4021098 ]
 [ 0.00061829]
 [-0.00242261]]
Z2 : 
 [[ 0.68170768]
 [ 0.513632  ]
 [ 0.00089854]
 [-0.00681818]]
X2 : 
 [[ 0.63579542]
 [ 0.47976665]
 [ 0.00152576]
 [-0.00495945]]
Z3 : 
 [[4.64254379e-01]
 [5.10598302e-01]
 [5.04255295e-04]
 [1.04427338e-02]]
X3 : 
 [[5.16264286e-01]
 [5.01227275e-01]
 [7.29437979e-06]
 [5.91593890e-03]]
Z4 : 
 [[ 0.61363661]
 [ 0.49611765]
 [-0.13536304]
 [ 0.66135138]]
X4 : 
 [[ 0.58349262]
 [ 0.50086684]
 [-0.09383158]
 [ 0.46245501]]
Z5 : 
 [[0.49542326]
 [0.55825567]
 [0.01011997]
 [0.07092208]]
X5 : 
 [[ 0.52070487]
 [ 0.54836675]
 [-0.02180534]
 [ 0.18984482]]
Z6 : 
 [[6.17376208e-01]
 [7.13096619e-01]
 [1.89542770e-04]
 [1.66323781e-02]]
X6 : 
 [[ 0.58774375]
 [ 0.66619789]
 [-0.0060228 ]
 [ 0.06990295]]
Z7 : 
 [

Z0 : 
 [[ 0.65463156]
 [ 0.32101715]
 [-0.01180977]
 [ 0.00852048]]
X0 : 
 [[ 0.61982438]
 [ 0.59690841]
 [-0.00846937]
 [-0.04250303]]
Z1 : 
 [[ 0.49665943]
 [ 0.31504047]
 [-0.01020536]
 [ 0.05213946]]
X1 : 
 [[ 0.53380413]
 [ 0.40004412]
 [-0.01025498]
 [ 0.02211153]]
Z2 : 
 [[ 0.68381393]
 [ 0.53057575]
 [-0.00897378]
 [ 0.00579   ]]
X2 : 
 [[ 0.63815373]
 [ 0.49138936]
 [-0.0086541 ]
 [ 0.01134894]]
Z3 : 
 [[0.45425716]
 [0.5109129 ]
 [0.00170946]
 [0.02624452]]
X3 : 
 [[ 0.50985915]
 [ 0.50529578]
 [-0.00229682]
 [ 0.02181317]]
Z4 : 
 [[0.59964418]
 [0.56805736]
 [0.00079751]
 [0.01537085]]
X4 : 
 [[5.72403828e-01]
 [5.49448456e-01]
 [2.81441991e-04]
 [1.76137683e-02]]
Z5 : 
 [[ 0.49971309]
 [ 0.5551967 ]
 [-0.03115162]
 [-0.00861794]]
X5 : 
 [[ 0.52159925]
 [ 0.55368728]
 [-0.0219561 ]
 [-0.00063728]]
Z6 : 
 [[6.10812664e-01]
 [7.30777919e-01]
 [2.23517418e-04]
 [1.36113167e-02]]
X6 : 
 [[ 0.58343808]
 [ 0.67716639]
 [-0.00607988]
 [ 0.01012076]]
Z7 : 
 [[ 0.51858634]
 [ 0.71368

Z0 : 
 [[ 0.65789956]
 [ 0.31142026]
 [-0.00131428]
 [ 0.00086188]]
X0 : 
 [[ 0.62520623]
 [ 0.57272561]
 [-0.00069762]
 [-0.06126667]]
Z1 : 
 [[ 4.99047577e-01]
 [ 3.16917330e-01]
 [-2.25082040e-03]
 [ 4.47034836e-05]]
X1 : 
 [[ 0.53725736]
 [ 0.39348808]
 [-0.00237241]
 [-0.0197416 ]]
Z2 : 
 [[ 0.68958294]
 [ 0.52054775]
 [ 0.00085473]
 [-0.00163615]]
X2 : 
 [[ 6.43389364e-01]
 [ 4.81729802e-01]
 [ 5.92395381e-04]
 [-6.52615346e-03]]
Z3 : 
 [[ 0.46445626]
 [ 0.51482636]
 [-0.00715569]
 [ 0.00292897]]
X3 : 
 [[ 5.18655782e-01]
 [ 5.04709364e-01]
 [-5.64614667e-03]
 [ 2.17757471e-04]]
Z4 : 
 [[ 0.61503541]
 [ 0.56961787]
 [ 0.02856463]
 [-0.0071454 ]]
X4 : 
 [[ 0.58587524]
 [ 0.54991775]
 [ 0.01863934]
 [-0.00460622]]
Z5 : 
 [[0.51080954]
 [0.55950356]
 [0.00961751]
 [0.00971496]]
X5 : 
 [[0.53389164]
 [0.55657293]
 [0.01199616]
 [0.00541617]]
Z6 : 
 [[ 0.61823589]
 [ 0.71337926]
 [-0.00159591]
 [ 0.00335455]]
X6 : 
 [[0.59285462]
 [0.66596032]
 [0.00292091]
 [0.00471554]]
Z7 : 
 [[ 5.

Z0 : 
 [[ 0.64891291]
 [ 0.31514201]
 [-0.02047688]
 [ 0.03167689]]
X0 : 
 [[ 0.61708962]
 [ 0.5887273 ]
 [-0.00722575]
 [ 0.03967607]]
Z1 : 
 [[0.50184357]
 [0.31805566]
 [0.00325441]
 [0.04157111]]
X1 : 
 [[ 5.36671079e-01]
 [ 4.00890604e-01]
 [-4.64964288e-04]
 [ 3.97112416e-02]]
Z2 : 
 [[ 0.68186617]
 [ 0.52065897]
 [-0.00911057]
 [-0.00954688]]
X2 : 
 [[ 0.63781614]
 [ 0.48493501]
 [-0.00580463]
 [ 0.00594949]]
Z3 : 
 [[0.47158694]
 [0.50523996]
 [0.03165588]
 [0.03439575]]
X3 : 
 [[0.52201996]
 [0.49934066]
 [0.01951007]
 [0.02585825]]
Z4 : 
 [[ 0.66821295]
 [ 0.33956882]
 [ 0.25850236]
 [-0.24477392]]
X4 : 
 [[ 0.62542823]
 [ 0.38723631]
 [ 0.1866691 ]
 [-0.16341863]]
Z5 : 
 [[ 0.5166418 ]
 [ 0.55715084]
 [-0.00300944]
 [ 0.09448886]]
X5 : 
 [[0.55248802]
 [0.5035708 ]
 [0.05397241]
 [0.01708525]]
Z6 : 
 [[0.62059361]
 [0.71224195]
 [0.01010031]
 [0.02712965]]
X6 : 
 [[0.600839  ]
 [0.64939852]
 [0.02371512]
 [0.02505763]]
Z7 : 
 [[0.53184533]
 [0.70835793]
 [0.00262499]
 [0.051

Z0 : 
 [[0.65031159]
 [0.30901209]
 [0.00083685]
 [0.00130579]]
X0 : 
 [[0.61849965]
 [0.6047623 ]
 [0.00433234]
 [0.05420111]]
Z1 : 
 [[ 0.49106407]
 [ 0.31574672]
 [-0.00858217]
 [ 0.00418782]]
X1 : 
 [[ 0.52970903]
 [ 0.40419004]
 [-0.00526413]
 [ 0.01798705]]
Z2 : 
 [[6.83637977e-01]
 [5.13667345e-01]
 [2.53915787e-04]
 [9.78559256e-03]]
X2 : 
 [[ 0.63691086]
 [ 0.48081612]
 [-0.00069507]
 [ 0.01278308]]
Z3 : 
 [[ 0.45716429]
 [ 0.51376319]
 [-0.00243634]
 [ 0.00257492]]
X3 : 
 [[ 0.51161255]
 [ 0.50398916]
 [-0.00275279]
 [ 0.00582313]]
Z4 : 
 [[0.61214584]
 [0.55961502]
 [0.01284331]
 [0.04880369]]
X4 : 
 [[0.58169789]
 [0.54307782]
 [0.00858466]
 [0.03602232]]
Z5 : 
 [[ 0.50874788]
 [ 0.56184715]
 [-0.01970351]
 [ 0.01555234]]
X5 : 
 [[ 0.53089513]
 [ 0.5567908 ]
 [-0.01146602]
 [ 0.02184023]]
Z6 : 
 [[6.15136266e-01]
 [7.17106044e-01]
 [4.00543213e-04]
 [1.60038471e-04]]
X6 : 
 [[ 0.58943193]
 [ 0.66886334]
 [-0.00280036]
 [ 0.00748499]]
Z7 : 
 [[ 0.52511036]
 [ 0.70394433]
 [-

Z0 : 
 [[0.65124482]
 [0.3216826 ]
 [0.02363831]
 [0.01382187]]
X0 : 
 [[0.62010101]
 [0.60487215]
 [0.0183919 ]
 [0.02501543]]
Z1 : 
 [[0.49894872]
 [0.31752089]
 [0.03779992]
 [0.00626296]]
X1 : 
 [[0.53612558]
 [0.40501718]
 [0.03133588]
 [0.01059409]]
Z2 : 
 [[ 6.80225790e-01]
 [ 5.32950819e-01]
 [-1.70767307e-04]
 [ 1.38938427e-02]]
X2 : 
 [[0.63704254]
 [0.49441129]
 [0.0100565 ]
 [0.01349074]]
Z3 : 
 [[0.46539325]
 [0.5036822 ]
 [0.01279995]
 [0.00860274]]
X3 : 
 [[0.517626  ]
 [0.50112231]
 [0.01115745]
 [0.0101252 ]]
Z4 : 
 [[ 0.63667262]
 [ 0.42630059]
 [-0.00089049]
 [ 0.06478563]]
X4 : 
 [[0.60076544]
 [0.44943612]
 [0.00332121]
 [0.04784579]]
Z5 : 
 [[ 0.51564807]
 [ 0.55347097]
 [ 0.00666618]
 [-0.00468493]]
X5 : 
 [[0.5415249 ]
 [0.52266386]
 [0.00525008]
 [0.01172789]]
Z6 : 
 [[6.16042674e-01]
 [7.06737697e-01]
 [2.48551369e-04]
 [4.01437283e-03]]
X6 : 
 [[0.59354332]
 [0.65115654]
 [0.00211477]
 [0.00721646]]
Z7 : 
 [[ 0.52669883]
 [ 0.69020909]
 [ 0.02201825]
 [-0.026

Z0 : 
 [[0.64698803]
 [0.31000882]
 [0.01167208]
 [0.02734825]]
X0 : 
 [[ 0.61225264]
 [ 0.59922124]
 [-0.02237827]
 [ 0.02827901]]
Z1 : 
 [[ 0.49035239]
 [ 0.31720722]
 [ 0.0135456 ]
 [-0.02929151]]
X1 : 
 [[ 0.52700988]
 [ 0.40296956]
 [ 0.00207963]
 [-0.01315825]]
Z2 : 
 [[0.68077934]
 [0.51284194]
 [0.02907157]
 [0.07866383]]
X2 : 
 [[0.63434987]
 [0.47971199]
 [0.02160398]
 [0.05132406]]
Z3 : 
 [[ 4.59272385e-01]
 [ 5.14683962e-01]
 [ 1.65402889e-04]
 [-6.21977448e-02]]
X3 : 
 [[ 0.51266363]
 [ 0.50458925]
 [ 0.00584042]
 [-0.02760494]]
Z4 : 
 [[ 0.69506443]
 [ 0.37464476]
 [-0.27389288]
 [-1.3388662 ]]
X4 : 
 [[ 0.63859254]
 [ 0.40730118]
 [-0.18816129]
 [-0.94160899]]
Z5 : 
 [[0.51493204]
 [0.55619407]
 [0.01580536]
 [0.00231922]]
X5 : 
 [[ 0.54956367]
 [ 0.49648792]
 [-0.04660403]
 [-0.28308993]]
Z6 : 
 [[ 0.61818755]
 [ 0.71987498]
 [-0.0030005 ]
 [ 0.00180781]]
X6 : 
 [[ 0.59665519]
 [ 0.64779979]
 [-0.01589335]
 [-0.08349623]]
Z7 : 
 [[ 0.52512199]
 [ 0.71647263]
 [-0.003048

Z0 : 
 [[ 6.52128816e-01]
 [ 3.16735893e-01]
 [-1.85966492e-04]
 [ 2.43499875e-03]]
X0 : 
 [[0.62129311]
 [0.6024895 ]
 [0.00627802]
 [0.01333234]]
Z1 : 
 [[4.91240680e-01]
 [3.18645298e-01]
 [1.49309635e-04]
 [1.85966492e-04]]
X1 : 
 [[0.53074986]
 [0.40486914]
 [0.00139551]
 [0.00283625]]
Z2 : 
 [[ 0.68620479]
 [ 0.52845979]
 [-0.00190973]
 [ 0.00290841]]
X2 : 
 [[ 6.39108304e-01]
 [ 4.91064453e-01]
 [-1.76496231e-04]
 [ 3.46663531e-03]]
Z3 : 
 [[ 4.57922697e-01]
 [ 5.22818327e-01]
 [-4.51505184e-05]
 [ 7.52717257e-03]]
X3 : 
 [[ 0.51282633]
 [ 0.51328474]
 [-0.00093671]
 [ 0.00644333]]
Z4 : 
 [[ 0.6004135 ]
 [ 0.57896167]
 [-0.00723928]
 [ 0.00061601]]
X4 : 
 [[ 0.57382249]
 [ 0.55916168]
 [-0.00491493]
 [ 0.00269085]]
Z5 : 
 [[ 0.50671035]
 [ 0.57241225]
 [-0.00303537]
 [-0.0105688 ]]
X5 : 
 [[ 0.52695759]
 [ 0.56838882]
 [-0.00391962]
 [-0.00648414]]
Z6 : 
 [[ 6.18590415e-01]
 [ 7.28684723e-01]
 [ 2.68220901e-06]
 [-4.78327274e-04]]
X6 : 
 [[ 0.59076121]
 [ 0.68000581]
 [-0.000755

Z0 : 
 [[ 6.61069036e-01]
 [ 3.18647444e-01]
 [ 9.83476639e-06]
 [-1.55881047e-03]]
X0 : 
 [[0.62838142]
 [0.61290579]
 [0.01194505]
 [0.01663431]]
Z1 : 
 [[ 5.05145788e-01]
 [ 3.21372390e-01]
 [-2.95042992e-05]
 [ 6.07967377e-05]]
X1 : 
 [[0.54267621]
 [0.40997696]
 [0.0030207 ]
 [0.00371376]]
Z2 : 
 [[ 0.69353849]
 [ 0.5234319 ]
 [ 0.00858933]
 [-0.03377885]]
X2 : 
 [[ 0.64790831]
 [ 0.48894923]
 [ 0.00760798]
 [-0.02187074]]
Z3 : 
 [[0.47477475]
 [0.51811886]
 [0.00665769]
 [0.00402868]]
X3 : 
 [[ 0.52739046]
 [ 0.50895919]
 [ 0.00612973]
 [-0.00368567]]
Z4 : 
 [[0.6262536 ]
 [0.5821119 ]
 [0.01271188]
 [0.01653492]]
X4 : 
 [[0.59644885]
 [0.55996426]
 [0.01117758]
 [0.0107447 ]]
Z5 : 
 [[ 0.53217781]
 [ 0.49287462]
 [-0.00345469]
 [ 0.25595471]]
X5 : 
 [[0.55181157]
 [0.51457532]
 [0.00067935]
 [0.18123498]]
Z6 : 
 [[ 0.62402356]
 [ 0.72588748]
 [ 0.01640439]
 [-0.0011605 ]]
X6 : 
 [[0.60222805]
 [0.66465532]
 [0.0119724 ]
 [0.05511805]]
Z7 : 
 [[0.53301895]
 [0.7168442 ]
 [0.00564

Z0 : 
 [[ 0.62008852]
 [ 0.31921294]
 [-0.02523065]
 [ 0.0236088 ]]
X0 : 
 [[ 0.59990979]
 [ 0.60344124]
 [-0.01894807]
 [ 0.0518631 ]]
Z1 : 
 [[ 0.47216088]
 [ 0.32841891]
 [-0.02164274]
 [ 0.04625827]]
X1 : 
 [[ 0.5104785 ]
 [ 0.41278324]
 [-0.02141975]
 [ 0.04664972]]
Z2 : 
 [[0.65339959]
 [0.52592897]
 [0.02538353]
 [0.07541835]]
X2 : 
 [[0.609876  ]
 [0.49271893]
 [0.0118612 ]
 [0.06720674]]
Z3 : 
 [[0.44209036]
 [0.51476222]
 [0.0036563 ]
 [0.01358807]]
X3 : 
 [[0.49313726]
 [0.5091879 ]
 [0.00535332]
 [0.02993947]]
Z4 : 
 [[0.61573726]
 [0.45980686]
 [0.06761223]
 [0.67149594]]
X4 : 
 [[0.57898533]
 [0.47839218]
 [0.04929647]
 [0.47659504]]
Z5 : 
 [[ 0.48893851]
 [ 0.5675742 ]
 [-0.03239617]
 [ 0.01176685]]
X5 : 
 [[ 0.51683822]
 [ 0.54799175]
 [-0.00804797]
 [ 0.15307368]]
Z6 : 
 [[ 5.91267705e-01]
 [ 7.01249897e-01]
 [-6.07967377e-05]
 [-3.43537331e-02]]
X6 : 
 [[ 0.56858751]
 [ 0.65701786]
 [-0.00213182]
 [ 0.0231875 ]]
Z7 : 
 [[ 0.50465387]
 [ 0.70664638]
 [-0.01291484]
 [-0

Z0 : 
 [[0.6503219 ]
 [0.3110939 ]
 [0.00644535]
 [0.00986964]]
X0 : 
 [[ 0.61899999]
 [ 0.59277993]
 [ 0.00900492]
 [-0.0158212 ]]
Z1 : 
 [[ 4.93921846e-01]
 [ 3.17606926e-01]
 [ 2.07826495e-03]
 [-1.94460154e-04]]
X1 : 
 [[ 0.53197495]
 [ 0.40074932]
 [ 0.00358911]
 [-0.00622453]]
Z2 : 
 [[0.67895615]
 [0.52054268]
 [0.01522064]
 [0.01188219]]
X2 : 
 [[0.63454208]
 [0.48419981]
 [0.01238128]
 [0.0069534 ]]
Z3 : 
 [[ 0.463144  ]
 [ 0.51378995]
 [-0.00908598]
 [-0.00645608]]
X3 : 
 [[ 0.51523378]
 [ 0.50490038]
 [-0.00338208]
 [-0.00225048]]
Z4 : 
 [[0.60698164]
 [0.5726319 ]
 [0.07047951]
 [0.06472439]]
X4 : 
 [[0.57945722]
 [0.55237589]
 [0.048501  ]
 [0.04472216]]
Z5 : 
 [[ 0.51319385]
 [ 0.56886196]
 [-0.08123428]
 [ 0.04236549]]
X5 : 
 [[ 0.53364429]
 [ 0.56475844]
 [-0.04219705]
 [ 0.04314403]]
Z6 : 
 [[ 6.17116690e-01]
 [ 7.12936223e-01]
 [-1.69873238e-05]
 [ 3.88205051e-02]]
X6 : 
 [[ 0.59116697]
 [ 0.66888365]
 [-0.01240952]
 [ 0.04081541]]
Z7 : 
 [[ 0.52781302]
 [ 0.70886737]

Z0 : 
 [[ 0.63632911]
 [ 0.31068093]
 [ 0.00817269]
 [-0.02700269]]
X0 : 
 [[ 0.61061682]
 [ 0.59730716]
 [ 0.01003528]
 [-0.03814287]]
Z1 : 
 [[ 0.48957497]
 [ 0.31446233]
 [ 0.00688031]
 [-0.03153116]]
X1 : 
 [[ 0.52644346]
 [ 0.39943627]
 [ 0.00726541]
 [-0.03485498]]
Z2 : 
 [[0.66863883]
 [0.50224882]
 [0.03586203]
 [0.00207424]]
X2 : 
 [[ 0.62582909]
 [ 0.4705619 ]
 [ 0.02785151]
 [-0.00863647]]
Z3 : 
 [[ 0.45644426]
 [ 0.50767112]
 [ 0.00332236]
 [-0.03965199]]
X3 : 
 [[ 0.50822209]
 [ 0.49610523]
 [ 0.00995991]
 [-0.03006418]]
Z4 : 
 [[ 0.60036033]
 [ 0.40041736]
 [-0.10522038]
 [ 0.01165375]]
X4 : 
 [[ 0.57209846]
 [ 0.4290034 ]
 [-0.06984265]
 [-0.00144461]]
Z5 : 
 [[ 0.50058931]
 [ 0.57777911]
 [-0.02900183]
 [ 0.00625849]]
X5 : 
 [[ 0.52104047]
 [ 0.53270107]
 [-0.04170793]
 [ 0.00462109]]
Z6 : 
 [[0.60905057]
 [0.70051861]
 [0.00078052]
 [0.07138699]]
X6 : 
 [[ 0.58173707]
 [ 0.65007033]
 [-0.0116844 ]
 [ 0.05191653]]
Z7 : 
 [[5.21989763e-01]
 [6.97838724e-01]
 [3.90708447e

Z0 : 
 [[ 0.63471866]
 [ 0.29737636]
 [-0.01764536]
 [ 0.00267059]]
X0 : 
 [[ 0.61112809]
 [ 0.59192569]
 [-0.00913767]
 [ 0.00667865]]
Z1 : 
 [[ 0.48910674]
 [ 0.30947357]
 [-0.0191541 ]
 [ 0.00773683]]
X1 : 
 [[ 0.52585246]
 [ 0.39520791]
 [-0.01668571]
 [ 0.00608584]]
Z2 : 
 [[ 0.67834121]
 [ 0.49653935]
 [ 0.00343859]
 [-0.0052768 ]]
X2 : 
 [[ 0.63188845]
 [ 0.46590135]
 [-0.00194538]
 [-0.00135472]]
Z3 : 
 [[ 0.45801711]
 [ 0.51526994]
 [-0.00376806]
 [ 0.01913309]]
X3 : 
 [[ 0.5106593 ]
 [ 0.5003782 ]
 [-0.0040318 ]
 [ 0.01314924]]
Z4 : 
 [[ 0.66460776]
 [ 0.33119139]
 [ 0.05585432]
 [-0.19355714]]
X4 : 
 [[ 0.61815522]
 [ 0.38175576]
 [ 0.03840882]
 [-0.13163832]]
Z5 : 
 [[0.52037311]
 [0.53910029]
 [0.0594753 ]
 [0.10859102]]
X5 : 
 [[0.55088004]
 [0.48988841]
 [0.05261165]
 [0.03648221]]
Z6 : 
 [[0.61921966]
 [0.69215637]
 [0.00970781]
 [0.02099007]]
X6 : 
 [[0.59937119]
 [0.6315252 ]
 [0.02303036]
 [0.0266301 ]]
Z7 : 
 [[0.53172147]
 [0.69372636]
 [0.00668764]
 [0.06655097]]


Z0 : 
 [[ 0.63252801]
 [ 0.3093822 ]
 [ 0.02934605]
 [-0.00434786]]
X0 : 
 [[ 0.59813557]
 [ 0.59502225]
 [ 0.01114739]
 [-0.0078416 ]]
Z1 : 
 [[0.47818717]
 [0.31790525]
 [0.00863001]
 [0.01115084]]
X1 : 
 [[0.51474977]
 [0.40181379]
 [0.00882644]
 [0.00408791]]
Z2 : 
 [[ 0.67081255]
 [ 0.52012736]
 [ 0.0302276 ]
 [-0.00137061]]
X2 : 
 [[0.62379813]
 [0.48433048]
 [0.02446501]
 [0.00084052]]
Z3 : 
 [[ 0.44902888]
 [ 0.52385724]
 [-0.00289366]
 [ 0.02201825]]
X3 : 
 [[0.50235669]
 [0.51199557]
 [0.00457817]
 [0.01577812]]
Z4 : 
 [[0.59815377]
 [0.48236051]
 [0.01686394]
 [0.118213  ]]
X4 : 
 [[0.56927362]
 [0.49214145]
 [0.01358514]
 [0.08698821]]
Z5 : 
 [[ 0.50469166]
 [ 0.50680774]
 [-0.03263175]
 [-0.04534006]]
X5 : 
 [[ 0.5243198 ]
 [ 0.50349857]
 [-0.01891661]
 [-0.00514768]]
Z6 : 
 [[0.60757554]
 [0.71116579]
 [0.02592802]
 [0.00639528]]
X6 : 
 [[0.58217433]
 [0.64818448]
 [0.0127187 ]
 [0.00387082]]
Z7 : 
 [[ 0.51626694]
 [ 0.71661836]
 [ 0.01738787]
 [-0.00215292]]
X7 : 
 [[ 5.

Z0 : 
 [[ 6.47206604e-01]
 [ 3.07847559e-01]
 [-7.22855330e-03]
 [ 6.03497028e-05]]
X0 : 
 [[0.61672731]
 [0.5972547 ]
 [0.00605489]
 [0.05170648]]
Z1 : 
 [[ 4.92041677e-01]
 [ 3.12817544e-01]
 [-5.05149364e-04]
 [-4.42564487e-04]]
X1 : 
 [[0.52991796]
 [0.39981298]
 [0.00089723]
 [0.014027  ]]
Z2 : 
 [[ 0.67666948]
 [ 0.5286839 ]
 [-0.00125796]
 [-0.05600452]]
X2 : 
 [[ 6.32205819e-01]
 [ 4.89584951e-01]
 [ 8.55715763e-05]
 [-3.41543099e-02]]
Z3 : 
 [[ 4.59847450e-01]
 [ 5.18999457e-01]
 [-8.47846270e-03]
 [-4.11272049e-05]]
X3 : 
 [[ 0.51204049]
 [ 0.50955603]
 [-0.00669028]
 [-0.01024268]]
Z4 : 
 [[0.63927686]
 [0.42744368]
 [0.07040173]
 [0.03311589]]
X4 : 
 [[0.60094634]
 [0.45232395]
 [0.04761092]
 [0.01957735]]
Z5 : 
 [[ 5.13797879e-01]
 [ 5.72805345e-01]
 [-1.84768438e-02]
 [ 2.15470791e-04]]
X5 : 
 [[0.54085858]
 [0.5365991 ]
 [0.00115072]
 [0.00665046]]
Z6 : 
 [[ 0.61657405]
 [ 0.71573359]
 [-0.00084221]
 [-0.01149595]]
X6 : 
 [[ 5.93643073e-01]
 [ 6.61497630e-01]
 [ 1.180595

Z0 : 
 [[ 0.64304554]
 [ 0.30520687]
 [-0.05153775]
 [-0.06537974]]
X0 : 
 [[ 0.61186548]
 [ 0.59624441]
 [-0.03446433]
 [-0.04593967]]
Z1 : 
 [[ 0.49299455]
 [ 0.3162418 ]
 [-0.0303635 ]
 [-0.00548244]]
X1 : 
 [[ 0.52834026]
 [ 0.40035602]
 [-0.03215578]
 [-0.01905978]]
Z2 : 
 [[ 0.69274938]
 [ 0.47739249]
 [-0.00110507]
 [-0.223791  ]]
X2 : 
 [[ 0.6424231 ]
 [ 0.45269981]
 [-0.00974342]
 [-0.16130387]]
Z3 : 
 [[ 4.62331146e-01]
 [ 5.12906492e-01]
 [-2.63661146e-03]
 [ 4.37200069e-04]]
X3 : 
 [[ 0.51674287]
 [ 0.49216301]
 [-0.00563651]
 [-0.04830426]]
Z4 : 
 [[ 0.61636841]
 [ 0.3584851 ]
 [ 0.03982097]
 [-0.24808601]]
X4 : 
 [[ 0.58627766]
 [ 0.39707986]
 [ 0.02649849]
 [-0.18808205]]
Z5 : 
 [[ 0.51852167]
 [ 0.56675071]
 [ 0.0278458 ]
 [-0.00539839]]
X5 : 
 [[ 0.53959615]
 [ 0.51239261]
 [ 0.02711017]
 [-0.0599712 ]]
Z6 : 
 [[ 0.61946672]
 [ 0.69856107]
 [-0.00209659]
 [-0.16067594]]
X6 : 
 [[ 0.5956731 ]
 [ 0.64045949]
 [ 0.00713223]
 [-0.12922639]]
Z7 : 
 [[ 0.52952176]
 [ 0.69760

Z0 : 
 [[ 0.63719153]
 [ 0.31283107]
 [-0.03580928]
 [ 0.02205312]]
X0 : 
 [[ 0.60842384]
 [ 0.58678247]
 [-0.02542834]
 [-0.02075727]]
Z1 : 
 [[ 0.48590112]
 [ 0.31185514]
 [-0.01692027]
 [-0.02899781]]
X1 : 
 [[ 0.52255674]
 [ 0.39471116]
 [-0.02006978]
 [-0.02778343]]
Z2 : 
 [[ 0.66316336]
 [ 0.51818711]
 [-0.06313115]
 [-0.00547707]]
X2 : 
 [[ 0.61994596]
 [ 0.48031246]
 [-0.04939829]
 [-0.01165603]]
Z3 : 
 [[ 0.44977659]
 [ 0.49887007]
 [-0.10441124]
 [-0.0103645 ]]
X3 : 
 [[ 0.5000882 ]
 [ 0.49301695]
 [-0.08850386]
 [-0.01066548]]
Z4 : 
 [[0.57919478]
 [0.59769857]
 [0.02895892]
 [0.24519414]]
X4 : 
 [[ 0.55398647]
 [ 0.56696314]
 [-0.00628171]
 [ 0.16805734]]
Z5 : 
 [[ 4.99749601e-01]
 [ 5.82728803e-01]
 [-3.10581923e-02]
 [ 1.45733356e-04]]
X5 : 
 [[ 0.51594219]
 [ 0.58055702]
 [-0.02379358]
 [ 0.05111448]]
Z6 : 
 [[ 6.02217019e-01]
 [ 7.06417382e-01]
 [-4.27553058e-02]
 [ 6.32107258e-04]]
X6 : 
 [[ 0.57550241]
 [ 0.66907192]
 [-0.03658895]
 [ 0.01652499]]
Z7 : 
 [[ 0.51476467

Z0 : 
 [[ 0.62176377]
 [ 0.30390695]
 [-0.01236051]
 [ 0.04121482]]
X0 : 
 [[ 0.59781753]
 [ 0.59599152]
 [-0.01760188]
 [ 0.05619319]]
Z1 : 
 [[ 0.4752593 ]
 [ 0.32603818]
 [-0.00844494]
 [ 0.00058562]]
X1 : 
 [[ 0.51208685]
 [ 0.40871882]
 [-0.01179395]
 [ 0.01617124]]
Z2 : 
 [[ 0.66389   ]
 [ 0.4914411 ]
 [-0.019041  ]
 [ 0.08985087]]
X2 : 
 [[ 0.61761516]
 [ 0.46704597]
 [-0.01612479]
 [ 0.06787901]]
Z3 : 
 [[0.44735989]
 [0.52388614]
 [0.00203758]
 [0.00837386]]
X3 : 
 [[ 0.49871375]
 [ 0.50775287]
 [-0.00426852]
 [ 0.02667469]]
Z4 : 
 [[ 0.65814221]
 [ 0.34816885]
 [ 0.5391553 ]
 [-0.18590435]]
X4 : 
 [[ 0.61229737]
 [ 0.39606882]
 [ 0.3750219 ]
 [-0.12216276]]
Z5 : 
 [[ 0.49342805]
 [ 0.54532254]
 [-0.08107468]
 [-0.1305145 ]]
X5 : 
 [[ 0.53488258]
 [ 0.49758534]
 [ 0.05663659]
 [-0.1272405 ]]
Z6 : 
 [[ 0.60055918]
 [ 0.6986019 ]
 [-0.01486659]
 [ 0.00839621]]
X6 : 
 [[ 0.58146458]
 [ 0.63575278]
 [ 0.00711972]
 [-0.03177345]]
Z7 : 
 [[ 0.51146072]
 [ 0.70089227]
 [-0.00786692]


Z0 : 
 [[ 0.63831985]
 [ 0.31741315]
 [ 0.06628633]
 [-0.00134245]]
X0 : 
 [[ 0.60784823]
 [ 0.60543477]
 [ 0.05304738]
 [-0.03758635]]
Z1 : 
 [[ 0.48402476]
 [ 0.32116714]
 [ 0.06005645]
 [-0.02612293]]
X1 : 
 [[ 0.52265294]
 [ 0.40660629]
 [ 0.05733105]
 [-0.03092571]]
Z2 : 
 [[ 0.66872752]
 [ 0.52515   ]
 [ 0.05005985]
 [-0.02145946]]
X2 : 
 [[ 0.62558506]
 [ 0.48864617]
 [ 0.0529348 ]
 [-0.02376471]]
Z3 : 
 [[ 0.45194131]
 [ 0.51975948]
 [ 0.10454133]
 [-0.00917673]]
X3 : 
 [[ 0.50587443]
 [ 0.50991935]
 [ 0.08805011]
 [-0.01344926]]
Z4 : 
 [[0.58286107]
 [0.53519833]
 [0.01117051]
 [0.08828312]]
X4 : 
 [[0.56094843]
 [0.52774432]
 [0.03483144]
 [0.0575388 ]]
Z5 : 
 [[0.50375372]
 [0.52385992]
 [0.01480222]
 [0.04225999]]
X5 : 
 [[0.52169557]
 [0.52612766]
 [0.02059964]
 [0.04685955]]
Z6 : 
 [[ 0.60546762]
 [ 0.72574294]
 [ 0.04183084]
 [-0.04979163]]
X6 : 
 [[ 0.58059727]
 [ 0.66574375]
 [ 0.03577629]
 [-0.01954227]]
Z7 : 
 [[ 0.51410353]
 [ 0.7238794 ]
 [ 0.06300867]
 [-0.0278896

Z0 : 
 [[0.64836979]
 [0.31426731]
 [0.00719368]
 [0.00273228]]
X0 : 
 [[ 0.61402972]
 [ 0.6038142 ]
 [ 0.00845368]
 [-0.0026089 ]]
Z1 : 
 [[0.49079806]
 [0.31576189]
 [0.00402868]
 [0.02905637]]
X1 : 
 [[0.52829223]
 [0.40314956]
 [0.00478933]
 [0.01809524]]
Z2 : 
 [[ 0.68088782]
 [ 0.52374011]
 [ 0.00893086]
 [-0.00165135]]
X2 : 
 [[0.6347614 ]
 [0.48746903]
 [0.00839011]
 [0.00490134]]
Z3 : 
 [[0.45717794]
 [0.50325829]
 [0.02885655]
 [0.01855999]]
X3 : 
 [[0.51125864]
 [0.49863674]
 [0.02180921]
 [0.01448841]]
Z4 : 
 [[ 0.59628677]
 [ 0.55943453]
 [ 0.00322491]
 [-0.04120141]]
X4 : 
 [[ 0.57087304]
 [ 0.54104124]
 [ 0.0092566 ]
 [-0.02402288]]
Z5 : 
 [[ 5.11640310e-01]
 [ 5.58077514e-01]
 [ 4.11272049e-05]
 [-8.12789798e-02]]
X5 : 
 [[ 0.52973391]
 [ 0.55216034]
 [ 0.0025559 ]
 [-0.06381887]]
Z6 : 
 [[0.61208349]
 [0.72046524]
 [0.022645  ]
 [0.00767916]]
X6 : 
 [[ 0.58727431]
 [ 0.66850884]
 [ 0.01693595]
 [-0.01320337]]
Z7 : 
 [[0.52023327]
 [0.71494329]
 [0.01087725]
 [0.0412407

Z0 : 
 [[ 6.52402997e-01]
 [ 3.18624914e-01]
 [-2.91466713e-04]
 [-4.31938469e-02]]
X0 : 
 [[ 0.62101829]
 [ 0.59062628]
 [ 0.01377639]
 [-0.09813657]]
Z1 : 
 [[ 4.98614252e-01]
 [ 3.11354727e-01]
 [-1.71661377e-04]
 [ 8.93801451e-03]]
X1 : 
 [[ 0.53592038]
 [ 0.39450606]
 [ 0.00348067]
 [-0.02483239]]
Z2 : 
 [[ 0.68108529]
 [ 0.52331185]
 [-0.00890315]
 [-0.0491783 ]]
X2 : 
 [[ 0.63710654]
 [ 0.48366235]
 [-0.00446434]
 [-0.04117802]]
Z3 : 
 [[0.46516871]
 [0.50902838]
 [0.01181871]
 [0.02912521]]
X3 : 
 [[0.5172592 ]
 [0.50084003]
 [0.00607125]
 [0.00792614]]
Z4 : 
 [[ 0.60016143]
 [ 0.56664002]
 [-0.02421945]
 [-0.01455992]]
X4 : 
 [[ 0.57501895]
 [ 0.54675438]
 [-0.0146409 ]
 [-0.00743041]]
Z5 : 
 [[0.52574015]
 [0.55992717]
 [0.19290894]
 [0.01318485]]
X5 : 
 [[0.54135354]
 [0.55588208]
 [0.12970764]
 [0.00699407]]
Z6 : 
 [[0.61464202]
 [0.71446431]
 [0.01474947]
 [0.01462787]]
X6 : 
 [[0.59451266]
 [0.66658465]
 [0.04993366]
 [0.01305496]]
Z7 : 
 [[0.5268178 ]
 [0.70732468]
 [0.0

Z0 : 
 [[0.64559519]
 [0.31212321]
 [0.01028538]
 [0.00562951]]
X0 : 
 [[0.61631954]
 [0.60276439]
 [0.00730086]
 [0.02596527]]
Z1 : 
 [[ 0.48999605]
 [ 0.32045805]
 [ 0.00095889]
 [-0.01624793]]
X1 : 
 [[ 0.52839487]
 [ 0.40633443]
 [ 0.00228701]
 [-0.00477499]]
Z2 : 
 [[ 0.68464518]
 [ 0.51933122]
 [ 0.0014627 ]
 [-0.00248909]]
X2 : 
 [[ 0.63733733]
 [ 0.48500289]
 [ 0.00244664]
 [-0.00264997]]
Z3 : 
 [[ 0.46169606]
 [ 0.51856893]
 [-0.00681505]
 [-0.06304979]]
X3 : 
 [[ 0.51492837]
 [ 0.50805958]
 [-0.00483136]
 [-0.04456481]]
Z4 : 
 [[0.60339922]
 [0.48968667]
 [0.08570641]
 [0.55092618]]
X4 : 
 [[0.57691698]
 [0.49715352]
 [0.0586531 ]
 [0.37017147]]
Z5 : 
 [[ 0.51179385]
 [ 0.57194489]
 [-0.07981449]
 [ 0.02636522]]
X5 : 
 [[ 0.5320628 ]
 [ 0.55514228]
 [-0.03812555]
 [ 0.13091759]]
Z6 : 
 [[ 6.17776275e-01]
 [ 7.18881071e-01]
 [-8.76188278e-05]
 [-2.90599465e-02]]
X6 : 
 [[ 0.5912102 ]
 [ 0.67115441]
 [-0.01121409]
 [ 0.02020873]]
Z7 : 
 [[ 0.52716631]
 [ 0.71554846]
 [-0.003203

Z0 : 
 [[ 0.62585092]
 [ 0.32309258]
 [-0.01016825]
 [ 0.00071079]]
X0 : 
 [[ 0.59974622]
 [ 0.60107868]
 [-0.01214761]
 [-0.10633079]]
Z1 : 
 [[ 4.71650034e-01]
 [ 3.25819701e-01]
 [-1.85671449e-02]
 [-4.54187393e-04]]
X1 : 
 [[ 0.51019277]
 [ 0.40758389]
 [-0.01721773]
 [-0.03383967]]
Z2 : 
 [[ 0.65556788]
 [ 0.53018945]
 [-0.01309901]
 [ 0.00734836]]
X2 : 
 [[ 0.61118485]
 [ 0.49254498]
 [-0.01365989]
 [-0.00456182]]
Z3 : 
 [[ 0.43990102]
 [ 0.51063782]
 [-0.00859603]
 [ 0.00663757]]
X3 : 
 [[ 0.4915548 ]
 [ 0.50511544]
 [-0.01093343]
 [ 0.00332597]]
Z4 : 
 [[ 0.5825935 ]
 [ 0.58668625]
 [-0.01789659]
 [ 0.01375973]]
X4 : 
 [[ 0.55475147]
 [ 0.56208324]
 [-0.01535244]
 [ 0.01097637]]
Z5 : 
 [[0.49778527]
 [0.59241694]
 [0.00158072]
 [0.02956152]]
X5 : 
 [[ 0.51481778]
 [ 0.58353372]
 [-0.00382009]
 [ 0.02406162]]
Z6 : 
 [[ 5.95014453e-01]
 [ 7.19904065e-01]
 [-1.60065293e-02]
 [-5.66840172e-04]]
X6 : 
 [[ 0.57057715]
 [ 0.67894866]
 [-0.01193074]
 [ 0.00753941]]
Z7 : 
 [[ 0.50211912